name: Maven CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B clean install

    - name: Run Tests
      run: |
        cd demo
        mvn test

    - name: Send Telegram Message
      uses: actions/checkout@v2
      with:
        token: "6798460403:AAHuTU9VjKd097co0dcfi6_TxP1NP4MCLGM"
        to: "-4229573400"
        message: "New commit pushed to repository"
        
